# -*- coding: utf-8 -*-
"""
Created on Sun May 17 03:43:22 2020

@author: 20111
"""
get_country ={
    'AF':'Afghanistan',
    'AL':'Albania',
    'DZ':'Algeria',
    'AD':'Andorra',
    'AO':'Angola',
    'AG':'Antigua and Barbuda',
    'AR':'Argentina',
    'AM':'Armenia',
    'AW': 'Aruba',
    'AU':'Australia',
    'AT':'Austria',
    'AZ':'Azerbaijan',
    'BS':'Bahamas',
    'BH':'Bahrain',
    'BD':'Bangladesh',
    'BB':'Barbados',
    'BY':'Belarus',
    'BE':'Belgium',
    'BZ':'Belize',
    'MM':'Burma',
    'BJ':'Benin',
    'BM':'Bermuda',
    'BT':'Bhutan',
    'BO':'Bolivia',
    'BA':'Bosnia and Herzegovina',
    'BR':'Brazil',
    'BN':'Brunei',
    'BG':'Bulgaria',
    'BF':'Burkina Faso',
    'CV':'Cabo Verde',
    'KH':'Cambodia',
    'CM':'Cameroon',
    'CA':'Canada',
    'CF':'Central African Republic',
    'TD':'Chad',
    'CL':'Chile',
    'CN':'China',
    'CO':'Colombia',
    'CG':'Congo (Brazzaville)',
    'CD':'Congo (Kinshasa)',
    'CR':'Costa Rica',
    'HR':'Croatia',
    'CI':"Cote d'Ivoire",
    'CU':'Cuba',
    'CY':'Cyprus',
    'CZ':'Czechia',
    'DK':'Denmark',
    'DJ':'Djibouti',
    'DM':'Dominica',
    'DO':'Dominican Republic',
    'EC':'Ecuador',
    'EG':'Egypt',
    'SV':'El Salvador',
    'GQ':'Equatorial Guinea',
    'ER':'Eritrea',
    'EE':'Estonia',
    'SZ':'Eswatini',
    'ET':'Ethiopia',
    'FJ':'Fiji',
    'FI':'Finland',
    'FR':'France',
    'GA':'Gabon',
    'GM':'Gambia',
    'GE':'Georgia',
    'DE':'Germany',
    'GH':'Ghana',
    'GD':'Grenada',
    'GR':'Greece',
    'GT':'Guatemala',
    'GN':'Guinea',
    'GW':'Guinea-Bissau',
    'GY':'Guyana',
    'HT':'Haiti',
    'VA':'Holy See',
    'HN':'Honduras',
    'HU': 'Hungary',
    'IS': 'Iceland',
    'IN': 'India',
    'ID': 'Indonesia',
    'IR':'Iran',
    'IQ':'Iraq',
    'IE':'Ireland',
    'IL':'Israel',
    'IT':'Italy',
    'LM':'Jamaica',
    'JP':'Japan',
    'JO':'Jordan',
    'KZ':'Kazakhstan',
    'KE':'Kenya',
    'KP':'Korea, South',
    'KW':'Kuwait',
    'KG':'Kyrgyzstan',
    'LV':'Latvia',
    'LB':'Lebanon',
    'LR':'Liberia',
    'LY':'Libya',
    'LI':'Liechtenstein',
    'LT':'Lithuania',
    'LU':'Luxembourg',
    'MG':'Madagascar',
    'MY':'Malaysia',
    'MV':'Maldives',
    'ML':'Mali',
    'MT':'Malta',
    'MR':'Mauritania',
    'MU':'Mauritius',
    'MX':'Mexico',
    'MD':'Moldova',
    'MC':'Monaco',
    'MN':'Mongolia',
    'ME':'Montenegro',
    'MO':'Morocco',
    'MZ':'Mozambique',
    'NA':'Namibia',
    'NP':'Nepal',
    'NL':'Netherlands',
    'NZ':'New Zealand',
    'NI':'Nicaragua',
    'NE':'Niger',
    'NG':'Nigeria',
    'MK':'North Macedonia',
    'NO':'Norway',
    'OM':'Oman',
    'PK':'Pakistan',
    'PA':'Panama',
    'PG':'Papua New Guinea',
    'PY':'Paraguay',
    'PE':'Peru',
    'PH':'Philippines',
    'PL':'Poland',
    'PT':'Portugal',
    'QA':'Qatar',
    'RO':'Romania',
    'RU':'Russia',
    'RW':'Rwanda',
    'KN':'Saint Kitts and Nevis',
    'LC':'Saint Lucia',
    'VC':'Saint Vincent and the Grenadines',
    'SM':'San Marino',
    'SA':'Saudi Arabia',
    'SN':'Senegal',
    'RS':'Serbia',
    'SC':'Seychelles',
    'SG':'Singapore',
    'SK':'Slovakia',
    'SI':'Slovenia',
    'SO':'Somalia',
    'ZA':'South Africa',
    'ES':'Spain',
    'LK':'Sri Lanka',
    'SD':'Sudan',
    'SR':'Suriname',
    'SE':'Sweden',
    'CH':'Switzerland',
    'SY':'Syria',
    'TW':'Taiwan*',
    'TZ':'Tanzania',
    'TH':'Thailand',
    'TL':'Timor-Leste',
    'TG':'Togo',
    'TT':'Trinidad and Tobago',
    'TN':'Tunisia',
    'TR':'Turkey',
    'UG':'Uganda',
    'UA':'Ukraine',
    'AE':'United Arab Emirates',
    'GB':'United Kingdom',
    'UY':'Uruguay',
    'US':'US',
    'UZ':'Uzbekistan',
    'VU':'Venezuela',
    'VN':'Vietnam',
    'ZM':'Zambia',
    'ZW':'Zimbabwe',
    'PS':'West Bank and Gaza',
    'BW':'Botswana',
    'BI':'Burundi',
    'SL':'Sierra Leone',
    'MW':'Malawi',
    'SS':'South Sudan',
    'EH':'Western Sahara',
    'ST':'Sao Tome and Principe',
    'YE':'Yemen',
    'KM':'Comoros',
    'TJ':'Tajikistan',
    'LS':'Lesotho'
           }





get_code ={
    'Afghanistan':'AF',
    'Albania':'AL',
    'Algeria':'DZ',
    'Andorra':'AD',
    'Angola':'AO',
    'Antigua and Barbuda':'AG',
    'Argentina':'AR',
    'Armenia':'AM',
    'Aruba':'AW',
    'Australia':'AU',
    'Austria':'AT',
    'Azerbaijan':'AZ',
    'Bahamas':'BS',
    'Bahrain':'BH',
    'Burma':'MM',
    'MS Zaandam': 'Ms Z',
    'Laos':'Laos',
    'Kosovo':'Kosovo',
    'Bangladesh':'BD',
    'Barbados':'BB',
    'Belarus':'BY',
    'Belgium':'BE',
    'Belize':'BZ',
    'Benin':'BJ',
    'Bermuda':'BM',
    'Bhutan':'BT',
    'Bolivia':'BO',
    'Bosnia and Herzegovina':'BA',
    'Brazil':'BR',
    'Diamond Princess':'D Pr',
    'Brunei':'BN',
    'Bulgaria':'BG',
    'Burkina Faso':'BF',
    'Cabo Verde':'CV',
    'Cambodia':'KH',
    'Cameroon':'CM',
    'Canada':'CA',
    'Central African Republic':'CF',
    'Chad':'TD',
    'Chile':'CL',
    'China':'CN',
    'Colombia':'CO',
    'Congo (Brazzaville)':'CG',
    'Congo (Kinshasa)':'CD',
    'Costa Rica':'CR',
    'Croatia':'HR',
    "Cote d'Ivoire":'CI',
    'Cuba':'CU',
    'Cyprus':'CY',
    'Czechia':'CZ',
    'Denmark':'DK',
    'Djibouti':'DJ',
    'Dominica':'DM',
    'Dominican Republic':'DO',
    'Ecuador':'EC',
    'Egypt':'EG',
    'El Salvador':'SV',
    'Equatorial Guinea':'GQ',
    'Eritrea':'ER',
    'Estonia':'EE',
    'Eswatini':'SZ',
    'Ethiopia':'ET',
    'Fiji':'FJ',
    'Finland':'FI',
    'France':'FR',
    'Gabon':'GA',
    'Gambia':'GM',
    'Georgia':'GE',
    'Germany':'DE',
    'Ghana':'GH',
    'Grenada':'GD',
    'Greece':'GR',
    'Guatemala':'GT',
    'Guinea':'GN',
    'Guinea-Bissau':'GW',
    'Guyana':'GY',
    'Haiti':'HT',
    'Holy See':'VA',
    'Honduras':'HN',
    'Hungary':'HU',
    'Iceland':'IS',
    'India':'IN',
    'Indonesia':'ID',
    'Iran':'IR',
    'Iraq':'IQ',
    'Ireland':'IE',
    'Israel':'IL',
    'Italy':'IT',
    'Jamaica':'LM',
    'Japan':'JP',
    'Jordan':'JO',
    'Kazakhstan':'KZ',
    'Kenya':'KE',
    'Korea, South':'KP',
    'Kuwait':'KW',
    'Kyrgyzstan':'KG',
    'Latvia':'LV',
    'Lebanon':'LB',
    'Liberia':'LR',
    'Libya':'LY',
    'Liechtenstein':'LI',
    'Lithuania':'LT',
    'Luxembourg':'LU',
    'Madagascar':'MG',
    'Malaysia':'MY',
    'Maldives':'MV',
    'Mali':'ML',
    'Malta':'MT',
    'Mauritania':'MR',
    'Mauritius':'MU',
    'Mexico':'MX',
    'Moldova':'MD',
    'Monaco':'MC',
    'Mongolia':'MN',
    'Montenegro':'ME',
    'Morocco':'MO',
    'Mozambique':'MZ',
    'Namibia':'NA',
    'Nepal':'NP',
    'Netherlands':'NL',
    'New Zealand':'NZ',
    'Nicaragua':'NI',
    'Niger':'NE',
    'Nigeria':'NG',
    'North Macedonia':'MK',
    'Norway':'NO',
    'Oman':'OM',
    'Pakistan':'PK',
    'Panama':'PA',
    'Papua New Guinea':'PG',
    'Paraguay':'PY',
    'Peru':'PE',
    'Philippines':'PH',
    'Poland':'PL',
    'Portugal':'PT',
    'Qatar':'QA',
    'Romania':'RO',
    'Russia':'RU',
    'Rwanda':'RW',
    'Saint Kitts and Nevis':'KN',
    'Saint Lucia':'LC',
    'Saint Vincent and the Grenadines':'VC',
    'San Marino':'SM',
    'Saudi Arabia':'SA',
    'Senegal':'SN',
    'Serbia':'RS',
    'Seychelles':'SC',
    'Singapore':'SG',
    'Slovakia':'SK',
    'Slovenia':'SI',
    'Somalia':'SO',
    'South Africa':'ZA',
    'Spain':'ES',
    'Sri Lanka':'LK',
    'Sudan':'SD',
    'Suriname':'SR',
    'Sweden':'SE',
    'Switzerland':'CH',
    'Syria':'SY',
    'Taiwan*':'TW',
    'Tanzania':'TZ',
    'Thailand':'TH',
    'Timor-Leste':'TL',
    'Togo':'TG',
    'Trinidad and Tobago':'TT',
    'Tunisia':'TN',
    'Turkey':'TR',
    'Uganda':'UG',
    'Ukraine':'UA',
    'United Arab Emirates':'AE',
    'United Kingdom':'GB',
    'Uruguay':'UY',
    'US':'US',
    'Uzbekistan':'UZ',
    'Venezuela':'VU',
    'Vietnam':'VN',
    'Zambia':'ZM',
    'Zimbabwe':'ZW',
    'West Bank and Gaza':'PS',
    'Botswana':'BW',
    'Burundi':'BI',
    'Sierra Leone':'SL',
    'Malawi':'MW',
    'South Sudan':'SS',
    'Western Sahara':'EH',
    'Sao Tome and Principe':'ST',
    'Yemen':'YE',
    'Comoros':'KM',
    'Tajikistan':'TJ',
    'Lesotho':'LS'
           }           
