# -*- coding: utf-8 -*-


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        font = QtGui.QFont()
        font.setPointSize(11)
        MainWindow.setFont(font)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setObjectName("verticalLayout")
        self.parameters_layout = QtWidgets.QHBoxLayout()
        self.parameters_layout.setObjectName("parameters_layout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setObjectName("label")
        self.parameters_layout.addWidget(self.label)
        self.discharge_velocity = QtWidgets.QLineEdit(self.centralwidget)
        self.discharge_velocity.setObjectName("discharge_velocity")
        self.discharge_velocity.setText("8")
        self.parameters_layout.addWidget(self.discharge_velocity)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.parameters_layout.addWidget(self.label_2)
        self.person_hieght = QtWidgets.QLineEdit(self.centralwidget)
        self.person_hieght.setObjectName("person_hieght")
        self.person_hieght.setText("1.7")
        self.parameters_layout.addWidget(self.person_hieght)
        self.add_mask = QtWidgets.QCheckBox(self.centralwidget)
        self.add_mask.setObjectName("add_mask")
        self.parameters_layout.addWidget(self.add_mask)
        self.select_mask = QtWidgets.QComboBox(self.centralwidget)
        self.select_mask.setObjectName("select_mask")
        self.select_mask.addItem("")
        self.select_mask.addItem("")
        self.parameters_layout.addWidget(self.select_mask)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.parameters_layout.addItem(spacerItem)
        self.verticalLayout.addLayout(self.parameters_layout)
        self.distance_layout = QtWidgets.QHBoxLayout()
        self.distance_layout.setObjectName("distance_layout")
        spacerItem1 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.distance_layout.addItem(spacerItem1)
        self.source_distance = QtWidgets.QLabel(self.centralwidget)
        self.source_distance.setObjectName("source_distance")
        self.distance_layout.addWidget(self.source_distance)
        self.distance_slider = QtWidgets.QSlider(self.centralwidget)
        self.distance_slider.setMinimum(1)
        self.distance_slider.setMaximum(10)
        self.distance_slider.setPageStep(1)
        self.distance_slider.setOrientation(QtCore.Qt.Horizontal)
        self.distance_slider.setTickPosition(QtWidgets.QSlider.TicksAbove)
        self.distance_slider.setObjectName("distance_slider")
        self.distance_layout.addWidget(self.distance_slider)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.distance_layout.addItem(spacerItem2)
        self.verticalLayout.addLayout(self.distance_layout)
        self.start_layout = QtWidgets.QHBoxLayout()
        self.start_layout.setObjectName("start_layout")
        spacerItem3 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.start_layout.addItem(spacerItem3)
        self.start_simulation = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.start_simulation.setFont(font)
        self.start_simulation.setFlat(True)
        self.start_simulation.setObjectName("start_simulation")
        self.start_layout.addWidget(self.start_simulation)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.start_layout.addItem(spacerItem4)
        self.verticalLayout.addLayout(self.start_layout)
        self.display_control_layout = QtWidgets.QVBoxLayout()
        self.display_control_layout.setObjectName("display_control_layout")
        self.display_layout = QtWidgets.QHBoxLayout()
        self.display_layout.setObjectName("display_layout")
        self.display_control_layout.addLayout(self.display_layout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.time_display = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.time_display.setFont(font)
        self.time_display.setObjectName("time_display")
        self.horizontalLayout_2.addWidget(self.time_display)
        self.distance_display = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.distance_display.setFont(font)
        self.distance_display.setObjectName("distance_display")
        self.horizontalLayout_2.addWidget(self.distance_display)
        spacerItem5 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem5)
        self.stop_simulation = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.stop_simulation.setFont(font)
        self.stop_simulation.setFlat(True)
        self.stop_simulation.setObjectName("stop_simulation")
        self.horizontalLayout_2.addWidget(self.stop_simulation)
        self.save_video = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.save_video.setFont(font)
        self.save_video.setFlat(True)
        self.save_video.setObjectName("save_video")
        self.horizontalLayout_2.addWidget(self.save_video)
        self.hide_plot = QtWidgets.QPushButton(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.hide_plot.setFont(font)
        self.hide_plot.setFlat(True)
        self.hide_plot.setObjectName("hide_plot")
        self.hide_plot.setText('Hide plot at point')
        self.horizontalLayout_2.addWidget(self.hide_plot)
        self.hide_plot.hide()
        self.horizontalLayout_2.setStretch(0, 1)
        self.horizontalLayout_2.setStretch(1, 1)
        self.horizontalLayout_2.setStretch(2, 1)
        self.horizontalLayout_2.setStretch(3, 1)
        self.horizontalLayout_2.setStretch(4, 1)
        self.horizontalLayout_2.setStretch(5, 1)
        self.display_control_layout.addLayout(self.horizontalLayout_2)
        self.display_control_layout.setStretch(0, 5)
        self.display_control_layout.setStretch(1, 1)
        self.verticalLayout.addLayout(self.display_control_layout)
        self.videoprogress = QtWidgets.QProgressBar(self.centralwidget)
        self.videoprogress.setProperty("value", 0)
        self.videoprogress.setObjectName("videoprogress")
        self.verticalLayout.addWidget(self.videoprogress)
        self.videoprogress.hide()
        self.frame = QtWidgets.QFrame()
        self.diplay_on_click_layout = QtWidgets.QHBoxLayout()
        self.diplay_on_click_layout.setObjectName("diplay_on_click_layout")
        self.frame.setLayout(self.diplay_on_click_layout)
        self.verticalLayout.addWidget(self.frame)
        self.frame.hide()
        self.verticalLayout.setStretch(0, 1)
        self.verticalLayout.setStretch(1, 1)
        self.verticalLayout.setStretch(2, 1)
        self.verticalLayout.setStretch(3, 6)
        self.verticalLayout.setStretch(5, 5)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Discharge Velocity"))
        self.label_2.setText(_translate("MainWindow", "Hieght"))
        self.add_mask.setText(_translate("MainWindow", "Add Mask"))
        self.select_mask.setItemText(0, _translate("MainWindow", "Tight Mask"))
        self.select_mask.setItemText(1, _translate("MainWindow", "Lossy Mask"))
        self.source_distance.setText(_translate("MainWindow", " 1 m From Source"))
        self.start_simulation.setText(_translate("MainWindow", "Start"))
        self.time_display.setText(_translate("MainWindow", "Time:"))
        self.distance_display.setText(_translate("MainWindow", "Distance:"))
        self.stop_simulation.setText(_translate("MainWindow", "stop"))
        self.save_video.setText(_translate("MainWindow", "Save Video"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
