# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project1.ui'
#
# Created by: PyQt5 UI code generator 5.13.2
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(716, 719)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
##################################################################       
##################################################################        
        self.orig_imgs = QtWidgets.QVBoxLayout()
        self.orig_imgs.setObjectName("orig_imgs")
        self.img_control = QtWidgets.QHBoxLayout()
        self.img_control.setObjectName("img_control")
        self.open_img = QtWidgets.QPushButton(self.centralwidget)
        self.open_img.setText("")
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("assets/icons/icons8-add-file-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.open_img.setIcon(icon)
        self.open_img.setIconSize(QtCore.QSize(30, 30))
        self.open_img.setFlat(True)
        self.open_img.setObjectName("open_img")
        self.img_control.addWidget(self.open_img)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.img_control.addItem(spacerItem)
        self.new_ch = QtWidgets.QPushButton(self.centralwidget)
        self.new_ch.setText("")
        icon1 = QtGui.QIcon()
        icon1.addPixmap(QtGui.QPixmap("assets/icons/icons8-add-new-200.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.new_ch.setIcon(icon1)
        self.new_ch.setIconSize(QtCore.QSize(35, 30))
        self.new_ch.setFlat(True)
        self.new_ch.setObjectName("new_ch")
        self.img_control.addWidget(self.new_ch)
        self.delete_ch = QtWidgets.QPushButton(self.centralwidget)
        self.delete_ch.setText("")
        icon2 = QtGui.QIcon()
        icon2.addPixmap(QtGui.QPixmap("assets/icons/icons8-clear-symbol-100.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.delete_ch.setIcon(icon2)
        self.delete_ch.setIconSize(QtCore.QSize(35, 30))
        self.delete_ch.setFlat(True)
        self.delete_ch.setObjectName("delete_ch")
        self.img_control.addWidget(self.delete_ch)
        self.orig_imgs.addLayout(self.img_control)
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents_2 = QtWidgets.QWidget()
        self.scrollAreaWidgetContents_2.setGeometry(QtCore.QRect(0, 0, 341, 608))
        self.scrollAreaWidgetContents_2.setObjectName("scrollAreaWidgetContents_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents_2)
        self.verticalLayout_2.setObjectName("verticalLayout_2")

        self.scrollArea.setWidget(self.scrollAreaWidgetContents_2)
        self.orig_imgs.addWidget(self.scrollArea)
        self.orig_imgs.setStretch(0, 1)
        self.orig_imgs.setStretch(1, 20)
        self.horizontalLayout.addLayout(self.orig_imgs)
        self.Mixer = QtWidgets.QVBoxLayout()
        self.Mixer.setObjectName("Mixer")
        self.output_control = QtWidgets.QVBoxLayout()
        self.output_control.setObjectName("output_control")
        self.wich_output = QtWidgets.QHBoxLayout()
        self.wich_output.setObjectName("wich_output")
        self.mixer_output_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.mixer_output_label.setFont(font)
        self.mixer_output_label.setObjectName("mixer_output_label")
        self.wich_output.addWidget(self.mixer_output_label)
        self.output_select = QtWidgets.QComboBox(self.centralwidget)
        self.output_select.setObjectName("output_select")
        self.output_select.addItem('NONE')
        self.wich_output.addWidget(self.output_select)
        self.output_control.addLayout(self.wich_output)
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.output_control.addItem(spacerItem1)
        self.output_comp1 = QtWidgets.QHBoxLayout()
        self.output_comp1.setObjectName("output_comp1")
        self.comp1_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comp1_label.setFont(font)
        self.comp1_label.setObjectName("comp1_label")
        self.output_comp1.addWidget(self.comp1_label)
        self.weight_1 = QtWidgets.QLineEdit(self.centralwidget)
        self.weight_1.setObjectName("weight_1")
        self.weight_1.setText("0")
        self.output_comp1.addWidget(self.weight_1)
        self.comp1_ratio = QtWidgets.QSlider(self.centralwidget)
        self.comp1_ratio.setOrientation(QtCore.Qt.Horizontal)
        self.comp1_ratio.setObjectName("comp1_ratio")
        self.comp1_ratio.setMaximum(100)
        self.comp1_ratio.setMinimum(0)
        self.comp1_ratio.setSingleStep(1)
        self.output_comp1.addWidget(self.comp1_ratio)
        self.output_comp1.setStretch(0, 2)
        self.output_comp1.setStretch(1, 1)
        self.output_comp1.setStretch(2, 4)
        self.output_control.addLayout(self.output_comp1)
        self.output_comp12 = QtWidgets.QHBoxLayout()
        self.output_comp12.setObjectName("output_comp12")
        
        self.img1_select = QtWidgets.QComboBox(self.centralwidget)
        self.img1_select.setObjectName("img1_select")               
        self.img1_select.addItem("none")
        self.output_comp12.addWidget(self.img1_select)
        self.comp1_select = QtWidgets.QComboBox(self.centralwidget)
        self.comp1_select.setObjectName("comp1_select")               
        self.comp1_select.addItem("none")                
        self.output_comp12.addWidget(self.comp1_select)
        self.img2_select = QtWidgets.QComboBox(self.centralwidget)
        self.img2_select.setObjectName("img2_select")               
        self.img2_select.addItem("none")
        self.output_comp12.addWidget(self.img2_select)
        self.comp2_select = QtWidgets.QComboBox(self.centralwidget)
        self.comp2_select.setObjectName("comp2_select")
        self.comp2_select.addItem("none")
        self.output_comp12.addWidget(self.comp2_select)

        self.output_control.addLayout(self.output_comp12)
        spacerItem4 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.output_control.addItem(spacerItem4)
        self.output_comp2 = QtWidgets.QHBoxLayout()
        self.output_comp2.setObjectName("output_comp2")
        self.comp2_label = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(14)
        self.comp2_label.setFont(font)
        self.comp2_label.setObjectName("comp2_label")
        self.output_comp2.addWidget(self.comp2_label)        
        self.weight_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.weight_2.setObjectName("weight_2")
        self.weight_2.setText("0")  
        self.output_comp2.addWidget(self.weight_2)
        self.comp2_ratio = QtWidgets.QSlider(self.centralwidget)
        self.comp2_ratio.setOrientation(QtCore.Qt.Horizontal)
        self.comp2_ratio.setObjectName("comp2_ratio")
        self.comp2_ratio.setMaximum(100)
        self.comp2_ratio.setMinimum(0)
        self.comp2_ratio.setSingleStep(1)
        self.output_comp2.addWidget(self.comp2_ratio)
        self.output_comp2.setStretch(0, 2)
        self.output_comp2.setStretch(1, 1)
        self.output_comp2.setStretch(2, 4)
        self.output_control.addLayout(self.output_comp2)
        self.output_comp22 = QtWidgets.QHBoxLayout()
        self.output_comp22.setObjectName("output_comp22")    
        self.img3_select = QtWidgets.QComboBox(self.centralwidget)
        self.img3_select.setObjectName("img3_select")               
        self.img3_select.addItem("none")
        self.output_comp22.addWidget(self.img3_select)
        self.comp3_select = QtWidgets.QComboBox(self.centralwidget)
        self.comp3_select.setObjectName("comp3_select")
        self.comp3_select.addItem("none")
        self.output_comp22.addWidget(self.comp3_select)
        self.img4_select = QtWidgets.QComboBox(self.centralwidget)
        self.img4_select.setObjectName("img4_select")               
        self.img4_select.addItem("none")
        self.output_comp22.addWidget(self.img4_select)
        self.comp4_select = QtWidgets.QComboBox(self.centralwidget)
        self.comp4_select.setObjectName("comp4_select")
        self.comp4_select.addItem("none")
        self.output_comp22.addWidget(self.comp4_select)
        self.output_control.addLayout(self.output_comp22)
        self.output_control.setStretch(0, 3)
        self.output_control.setStretch(1, 1)
        self.output_control.setStretch(2, 2)
        self.output_control.setStretch(3, 2)
        self.output_control.setStretch(4, 1)
        self.output_control.setStretch(5, 2)
        self.output_control.setStretch(6, 2)
        self.Mixer.addLayout(self.output_control)

        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.Mixer.addItem(spacerItem5)

        self.output_ch__control = QtWidgets.QHBoxLayout()
        self.output_ch__control.setObjectName("output_ch__control")
        self.save_img = QtWidgets.QPushButton(self.centralwidget)
        self.save_img.setText("")
        icon3 = QtGui.QIcon()
        icon3.addPixmap(QtGui.QPixmap("assets/icons/icons8-save-50.png"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        self.save_img.setIcon(icon3)
        self.save_img.setIconSize(QtCore.QSize(30, 30))
        self.save_img.setFlat(True)
        self.save_img.setObjectName("save_img")
        self.output_ch__control.addWidget(self.save_img)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.output_control.addItem(spacerItem8)
        self.new_ch_2 = QtWidgets.QPushButton(self.centralwidget)
        self.new_ch_2.setText("")
        self.new_ch_2.setIcon(icon1)
        self.new_ch_2.setIconSize(QtCore.QSize(35, 30))
        self.new_ch_2.setFlat(True)
        self.new_ch_2.setObjectName("new_ch_2")
        self.output_ch__control.addWidget(self.new_ch_2)
        self.delete_ch_2 = QtWidgets.QPushButton(self.centralwidget)
        self.delete_ch_2.setText("")
        self.delete_ch_2.setIcon(icon2)
        self.delete_ch_2.setIconSize(QtCore.QSize(35, 30))
        self.delete_ch_2.setFlat(True)
        self.delete_ch_2.setObjectName("delete_ch_2")
        self.output_ch__control.addWidget(self.delete_ch_2)
        self.Mixer.addLayout(self.output_ch__control)        
        self.output_area = QtWidgets.QScrollArea(self.centralwidget)
        self.output_area.setWidgetResizable(True)
        self.output_area.setObjectName("output_area")
        
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 341, 305))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.scrollAreaWidgetContents)
        self.verticalLayout.setObjectName("verticalLayout")        
        self.output_display = QtWidgets.QVBoxLayout()
        self.output_display.setObjectName("outpu1_display")
        self.verticalLayout.addLayout(self.output_display)
        self.verticalLayout.setStretch(0, 1)
        self.output_area.setWidget(self.scrollAreaWidgetContents)
        self.Mixer.addWidget(self.output_area)
        self.Mixer.setStretch(0, 6)
        self.Mixer.setStretch(1, 1)
        self.Mixer.setStretch(2, 2)
        self.Mixer.setStretch(3, 12)
        self.horizontalLayout.addLayout(self.Mixer)
        self.verticalLayout_3.addLayout(self.horizontalLayout)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 716, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.comp_combo_l = [self.comp1_select,self.comp2_select,self.comp3_select,self.comp4_select]
        self.img_combo_l = [self.img1_select,self.img2_select,self.img3_select,self.img4_select]
        self.ratio_l = [self.comp1_ratio,self.comp2_ratio]
        self.weight_l = [self.weight_1,self.weight_2]
        self.msg = QtWidgets.QMessageBox()
        self.msg.setIcon(QtWidgets.QMessageBox.Warning)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        
    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))

        self.mixer_output_label.setText(_translate("MainWindow", "Mixer Output To"))
        self.comp1_label.setText(_translate("MainWindow", "Component1:"))
        self.comp2_label.setText(_translate("MainWindow", "Component1:"))
        for i in self.weight_l:
            i.textChanged.connect(self.move_slider) 
        for i in self.ratio_l:
            i.valueChanged.connect(self.change_weight) 
        for i in self.comp_combo_l:
                i.addItem(f"ampl")
                i.addItem(f"phase")
                i.addItem(f"real")
                i.addItem(f"im")
                i.addItem(f"uni_amp")
                i.addItem(f"uni_ph")

                for ind in range(6):
                    i.view().setRowHidden( ind + 1 ,True)
    def change_weight(self):
        for i in range(2):
            temp = self.ratio_l[i].value()
            self.weight_l[i].setText(str(temp))
    def move_slider(self):
        for i in range(2):
             temp = int(self.weight_l[i].text())
             self.ratio_l[i].setValue(temp)
                                 

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
